#! /usr/bin/php
<?php

// Validation
if ($argc > 2) {
    if (is_file($argv[1])) {
        $file = $argv[1];
    } else
        exit('Please specify a valid path to target log file!');

    if (isset($argv[2]) && is_numeric($argv[2]) && $argv[2] > 0)
        $emailLimit = $argv[2];
    else
        exit('Please specify a valid number of emails limit!');
} else
    exit('Please specify a valid args!');

$file = new SplFileObject($file);

$emails = [];
$emailPattern = '/[\._a-zA-Z0-9-]+@[\._a-zA-Z0-9-]+/i';
$warningEmailList = [];

$startTime = microtime(true);

$fileSize = $file->getSize();
$percentage = 0;

passthru('tput reset');
passthru('tput civis');
passthru('tput cup 0 0');

echo 'Progress: ' . $percentage . '% ';

$percentage++;

$lengthFfAllReadedLines = strlen($file->fgets());
$averageLineLength = $lengthFfAllReadedLines;

$file->rewind();

while (!$file->eof()) {
    $averageLineNumber = $fileSize / $averageLineLength;
    $linePerPercent = $averageLineNumber / 100;

    if ($file->key() > ($linePerPercent * $percentage) && $percentage < 100) {
        $percentage++;
        passthru('tput cup 0 0');
        echo 'Progress: ' . $percentage . '% ';
    }

    $line = $file->fgets();

    $lengthFfAllReadedLines += strlen($line);
    $averageLineLength = ($lengthFfAllReadedLines / ($file->key() + 1));
    if (mb_strpos($line, 'status=')) {
        if (preg_match($emailPattern, $line, $matches)) {
            if (!isset($emails[$matches[0]])) {
                $emails[$matches[0]] = [];
                $emails[$matches[0]]['count'] = 0;
            }

            $emails[$matches[0]]['count']++;

            if ($emails[$matches[0]]['count'] >= $emailLimit) {
                $warningEmailList[$matches[0]] = $emails[$matches[0]]['count'];
            }
        }
    }
}

var_dump($warningEmailList);
echo 'Total time spent seconds: ' . (microtime(true) - $startTime) . PHP_EOL;
passthru('tput cnorm');